<?php
/**
 * PayoutApi
 * PHP version 5
 *
 * @category Class
 * @package  Algocash
 * @author   devstar
 * @link     https://github.com/Jax-Vinod/algocash-php-sdk
 */

/**
 * Algocash API
 *
 * This is a Algocash API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: loganph.work@gmail.com
 * Generated by: https://github.com/Jax-Vinod/algocash-php-sdk.git
 
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/Jax-Vinod/algocash-php-sdk
 * Do not edit the class manually.
 */

namespace Algocash\Api;

use Algocash\Algocash;
use Algocash\Model\PayoutRequest;
use Algocash\Model\PayoutSuccess;
use Algocash\Response;

/**
 * PayoutApi Class Doc Comment
 *
 * @category Class
 * @package  Algocash
 * @author   devstar
 * @link     https://github.com/Jax-Vinod/algocash-php-sdk
 */
class PayoutApi
{

    /**
     * @var Algocash
     */
    protected $algocash;

    /**
     * @param Algocash   $algocash
     */
    public function __construct(Algocash $algocash) {
        $this->algocash = $algocash;
    }

    /**
     * @return Response
     */

    private function request($path, $params = [], $type = 'GET') {
        return $this->algocash->request($path, $params, $type);
    }

    /**
     * Operation createPayout
     *
     * create payout
     * @param PayoutRequest $body
     *
     * @throws \Algocash\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Algocash\Model\PayoutSuccess
     */
    public function createPayout($body)
    {
        $response = $this->request('/payout', $body, 'POST');
        return new PayoutSuccess($response->contents());
    }  
}
