<?php
/**
 * UrlTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Algocash
 * @author   devstar
 * @link     https://github.com/Jax-Vinod/algocash-php-sdk
 */

/**
 * Algocash API
 *
 * This is a Algocash API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: loganph.work@gmail.com
 * Generated by: https://github.com/Jax-Vinod/algocash-php-sdk.git
 
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/Jax-Vinod/algocash-php-sdk
 * Please update the test case below to test the model.
 */

namespace Algocash;

use PHPUnit\Framework\TestCase;

/**
 * UrlTest Class Doc Comment
 *
 * @category    Class
 * @description Url
 * @package     Algocash
 * @author      devstar
 * @link        https://github.com/Jax-Vinod/algocash-php-sdk
 */
class UrlTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Url"
     */
    public function testUrl()
    {
    }

    /**
     * Test attribute "callback_url"
     */
    public function testPropertyCallbackUrl()
    {
    }

    /**
     * Test attribute "pending_url"
     */
    public function testPropertyPendingUrl()
    {
    }

    /**
     * Test attribute "success_url"
     */
    public function testPropertySuccessUrl()
    {
    }

    /**
     * Test attribute "error_url"
     */
    public function testPropertyErrorUrl()
    {
    }

    /**
     * Test attribute "back_url"
     */
    public function testPropertyBackUrl()
    {
    }
}
