<?php
/**
 * DepositApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Algocash
 * @author   devstar
 * @link     https://github.com/Jax-Vinod/algocash-php-sdk
 */

/**
 * Algocash API
 *
 * This is a Algocash API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: loganph.work@gmail.com
 * Generated by: https://github.com/Jax-Vinod/algocash-php-sdk.git
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/Jax-Vinod/algocash-php-sdk
 * Please update the test case below to test the endpoint.
 */

namespace Algocash;

use Algocash\Algocash;
use Algocash\ApiException;
use Algocash\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DepositApiTest Class Doc Comment
 *
 * @category Class
 * @package  Algocash
 * @author   devstar
 * @link     https://github.com/Jax-Vinod/algocash-php-sdk
 */
class DepositApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createDeposit
     *
     * create a deposit.
     *
     */
    public function testCreateDeposit()
    {
        $algo = Algocash::getInstance()
            ->setApiKey('', '')
            ->setAccessToken('YOUR_PASSWORD');
            // ->enableProdMode(false);
        // $algo->setHost('');

        $apiInstance = new \Algocash\Algocash\DepositApi(
            new \GuzzleHttp\Client(),
            $algo
        );
        $body = new \Algocash\Model\DepositRequest();

        try {
            $result = $apiInstance->createDeposit($body);
            print_r($result);
        } catch (\Exception $e) {
            echo 'Exception when calling DepositApi->createDeposit: ', $e->getMessage(), PHP_EOL;
        }
    }
}
