<?php
/**
 * PayoutApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Algocash
 * @author   devstar
 * @link     https://github.com/Jax-Vinod/algocash-php-sdk
 */

/**
 * Algocash API
 *
 * This is a Algocash API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: loganph.work@gmail.com
 * Generated by: https://github.com/Jax-Vinod/algocash-php-sdk.git
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/Jax-Vinod/algocash-php-sdk
 * Please update the test case below to test the endpoint.
 */

namespace Algocash;

use Algocash\Algocash;
use Algocash\Api\PayoutApi;
use Algocash\Model\Address;
use Algocash\Model\Bank;
use Algocash\Model\Payer;
use Algocash\Model\PayoutRequest;
use Algocash\Model\Url;
use PHPUnit\Framework\TestCase;

/**
 * PayoutApiTest Class Doc Comment
 *
 * @category Class
 * @package  Algocash
 * @author   devstar
 * @link     https://github.com/Jax-Vinod/algocash-php-sdk
 */
class PayoutApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createPayout
     *
     * create payout.
     *
     */
    public function testCreatePayout()
    {
        $algo = Algocash::getInstance()
            ->setApiKey('', '')
            ->setAccessToken('YOUR_PASSWORD');
            // ->enableProdMode(false);
        // $algo->setHost('');

        $apiInstance = new PayoutApi($algo);
        $address = new Address();
        $payer = new Payer("test@gmail.com", "+1231243", $address);
        $url = new Url("https://localhsot:8000/callback");
        $bank = new Bank("1231423", "fName lName", "sfsdf","2143");
        $body = new PayoutRequest("100001", "100", $payer, "UPI", $bank, $url);

        try {
            $result = $apiInstance->createPayout($body);
            print_r($result);
        } catch (\Algocash\ApiException $e) {
            echo 'Api Exception when calling DepositApi->createDeposit: ', json_encode($e->getError()), PHP_EOL;
        } catch (\Exception $e) {
            echo 'Exception when calling DepositApi->createDeposit: ', $e->getMessage(), PHP_EOL;
        }
    }
}
